#!/bin/bash

# CSE 374 Homework-2, Problem 1
# Students: Vaibhav Singh & David Maltby
# Date: 10/21/2021

if [ $# -ne 2 ]; then
    echo “$0 Requires 2 arguments” >&2
    exit 1
fi

if [ ! -f $2 ]; then
    echo "File does not exist" <& 1
    exit 1
fi

#grep -oE '(http|https)://(.*?)" ' courses-index.html > $2
# (?:(?!X).)
#grep -o -E "https?://[][[:alnum:]._~:/?#@!$&v(*+,;%-]+" courses-index.html > $1.txt
grep -o -E "http[s]?://courses.cs.washington.edu/courses/cse[p]?[0-9][0-9][0-9][.*]?/" $2 > $1